---
root: true

env:
  browser: true
  es6: true

parser: babel-eslint

extends:
  - eslint-config-airbnb-base
  - eslint-config-airbnb-base/rules/strict
  - eslint-config-airbnb/rules/react

rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    - never

